import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ReactNode } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'next repo test',
  description: 'Generated by create next app',
}

interface IProps {
  children: ReactNode
}

export default function RootLayout(props: IProps) {
  const { children } = props;

  return (
    <html lang="it">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
